# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movieAPP (iOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 6.0'

  # Pods for movieAPP (iOS)

end

target 'movieAPP (macOS)' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'SwiftyJSON', '~> 4.0'
  pod 'Kingfisher', '~> 6.0'

  # Pods for movieAPP (macOS)

end
